name: Deploy
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure corepack
        run: corepack enable

      - name: Instal deps
        run: pnpm i

      - name: Build
        run: pnpm docs:build

      - uses: actions/configure-pages@v2
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
